### ISSUE TITLE
Error while installing in certain system

### ISSUE THREAD

**Issue by seminumber** [brandontrabucco/design-bench#14]
Installing design-bench using pip failed in certain system due to `setup.py`:

```python
F = 'README.md'
with open(F, 'r') as readme:
    LONG_DESCRIPTION = readme.read()
```

Here's the traceback:
```
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "******\setup.py", line 7, in <module>
          LONG_DESCRIPTION = readme.read()
      UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 1798: illegal multibyte sequence
```

It seems the special characters in `README.md` cause the problem.

Here are a few solutions that may resolve the issue:

* Use the explicit long description instead of opening file
* Use `open()` with argument `errors='ignore'` so that encoding errors are ignored instead of raising error
* Use explicit `encoding='...'` that the file can be safely decoded in any platform and locale.

**Comment by brandontrabucco** [comment]
Hello [seminumber](https://github.com/seminumber),

Were you able to resolve this installation problem?
