### ISSUE TITLE
ValueError: Cannot load file containing pickled data when allow_pickle=False

### ISSUE THREAD

**Issue by Harkool** [brandontrabucco/design-bench#26]
Hello：
After following the instructions in the readme (reproducing Baseline Performance) and trying to create a new task, I get the following error:

```
`Traceback` (most recent call last):
  File "/user/liuh/miniconda3/envs/design-baselines/bin/design-baselines", line 33, in <module>
    sys.exit(load_entry_point('design-baselines', 'console_scripts', 'design-baselines')())
  File "/user/liuh/miniconda3/envs/design-baselines/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/user/liuh/miniconda3/envs/design-baselines/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/user/liuh/miniconda3/envs/design-baselines/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/user/liuh/miniconda3/envs/design-baselines/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/user/liuh/miniconda3/envs/design-baselines/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/user/liuh/SSP/Design/design-baselines-fixes/design_baselines/cli.py", line 841, in make_table
    tf_bind_8_dataset = TFBind8Dataset()
  File "/user/liuh/miniconda3/envs/design-baselines/lib/python3.7/site-packages/design_bench/datasets/discrete/tf_bind_8_dataset.py", line 294, in __init__
    soft_interpolation=soft_interpolation, **kwargs)
  File "/user/liuh/miniconda3/envs/design-baselines/lib/python3.7/site-packages/design_bench/datasets/discrete_dataset.py", line 279, in __init__
    super(DiscreteDataset, self).__init__(*args, **kwargs)
  File "/user/liuh/miniconda3/envs/design-baselines/lib/python3.7/site-packages/design_bench/datasets/dataset_builder.py", line 434, in __init__
    for x in self.iterate_samples(return_y=False):
  File "/user/liuh/miniconda3/envs/design-baselines/lib/python3.7/site-packages/design_bench/datasets/dataset_builder.py", line 842, in iterate_samples
    return_x=return_x, return_y=return_y):
  File "/user/liuh/miniconda3/envs/design-baselines/lib/python3.7/site-packages/design_bench/datasets/dataset_builder.py", line 738, in iterate_batches
    x_shard_data = self.get_shard_x(shard_id) if return_x else None
  File "/user/liuh/miniconda3/envs/design-baselines/lib/python3.7/site-packages/design_bench/datasets/dataset_builder.py", line 512, in get_shard_x
    return np.load(self.x_shards[shard_id].disk_target)
  File "/user/liuh/miniconda3/envs/design-baselines/lib/python3.7/site-packages/numpy/lib/npyio.py", line 445, in load
    raise ValueError("Cannot load file containing pickled data "
ValueError: Cannot load file containing pickled data when allow_pickle=False
```
In addition, taking one of the experiments as an example, the output looks like this:
```
== Status ==
Memory usage on this node: 254.7/376.6 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/20 CPUs, 0/1 GPUs, 0.0/80.53 GiB heap, 0.0/38.51 GiB objects (0.0/1.0 accelerator_type:G)
Result logdir: /user/liuh/db-results/reinforce-tf-bind-8/reinforce_2024-12-30_19-08-58
Number of trials: 8/8 (8 ERROR)
+-----------------------+----------+-------+
| Trial name            | status   | loc   |
|-----------------------+----------+-------|
| reinforce_77a90_00000 | ERROR    |       |
| reinforce_77a90_00001 | ERROR    |       |
| reinforce_77a90_00002 | ERROR    |       |
| reinforce_77a90_00003 | ERROR    |       |
| reinforce_77a90_00004 | ERROR    |       |
| reinforce_77a90_00005 | ERROR    |       |
| reinforce_77a90_00006 | ERROR    |       |
| reinforce_77a90_00007 | ERROR    |       |
+-----------------------+----------+-------+
Number of errored trials: 8
+-----------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------+
| Trial name            |   # failures | error file                                                                                                                    |
|-----------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------|
| reinforce_77a90_00000 |            1 | /user/liuh/db-results/reinforce-tf-bind-8/reinforce_2024-12-30_19-08-58/reinforce_77a90_00000_0_2024-12-30_19-08-58/error.txt |
| reinforce_77a90_00001 |            1 | /user/liuh/db-results/reinforce-tf-bind-8/reinforce_2024-12-30_19-08-58/reinforce_77a90_00001_1_2024-12-30_19-08-58/error.txt |
| reinforce_77a90_00002 |            1 | /user/liuh/db-results/reinforce-tf-bind-8/reinforce_2024-12-30_19-08-58/reinforce_77a90_00002_2_2024-12-30_19-08-58/error.txt |
| reinforce_77a90_00003 |            1 | /user/liuh/db-results/reinforce-tf-bind-8/reinforce_2024-12-30_19-08-58/reinforce_77a90_00003_3_2024-12-30_19-08-58/error.txt |
| reinforce_77a90_00004 |            1 | /user/liuh/db-results/reinforce-tf-bind-8/reinforce_2024-12-30_19-08-58/reinforce_77a90_00004_4_2024-12-30_19-08-58/error.txt |
| reinforce_77a90_00005 |            1 | /user/liuh/db-results/reinforce-tf-bind-8/reinforce_2024-12-30_19-08-58/reinforce_77a90_00005_5_2024-12-30_19-08-58/error.txt |
| reinforce_77a90_00006 |            1 | /user/liuh/db-results/reinforce-tf-bind-8/reinforce_2024-12-30_19-08-58/reinforce_77a90_00006_6_2024-12-30_19-08-58/error.txt |
| reinforce_77a90_00007 |            1 | /user/liuh/db-results/reinforce-tf-bind-8/reinforce_2024-12-30_19-08-58/reinforce_77a90_00007_7_2024-12-30_19-08-58/error.txt |
+-----------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------+

Traceback (most recent call last):
  File "/user/liuh/miniconda3/envs/design-baselines/bin/reinforce", line 33, in <module>
    sys.exit(load_entry_point('design-baselines', 'console_scripts', 'reinforce')())
  File "/user/liuh/miniconda3/envs/design-baselines/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/user/liuh/miniconda3/envs/design-baselines/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/user/liuh/miniconda3/envs/design-baselines/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/user/liuh/miniconda3/envs/design-baselines/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/user/liuh/miniconda3/envs/design-baselines/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/user/liuh/SSP/Design/design-baselines-fixes/design_baselines/reinforce/experiments.py", line 335, in tf_bind_8
    'gpu': gpus / num_parallel - 0.01})
  File "/user/liuh/miniconda3/envs/design-baselines/lib/python3.7/site-packages/ray/tune/tune.py", line 543, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [reinforce_77a90_00000, reinforce_77a90_00001, reinforce_77a90_00002, reinforce_77a90_00003, reinforce_77a90_00004, reinforce_77a90_00005, reinforce_77a90_00006, reinforce_77a90_00007])
2024-12-30 19:09:05.916442: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-12-30 19:09:06.054595: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-12-30 19:09:06.878505: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/user/liuh/.mujoco/mujoco200/bin:/user/liuh/.mujoco/mujoco200/bin:/user/liuh/.mujoco/mujoco200/bin:/user/liuh/.mujoco/mujoco200/bin:/user/liuh/.mujoco/mujoco200/bin:/home/liuh/.mujoco/mujoco200/bin
2024-12-30 19:09:06.878592: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/user/liuh/.mujoco/mujoco200/bin:/user/liuh/.mujoco/mujoco200/bin:/user/liuh/.mujoco/mujoco200/bin:/user/liuh/.mujoco/mujoco200/bin:/user/liuh/.mujoco/mujoco200/bin:/home/liuh/.mujoco/mujoco200/bin
2024-12-30 19:09:06.878603: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2024-12-30 19:09:07.898351: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/user/liuh/.mujoco/mujoco200/bin:/user/liuh/.mujoco/mujoco200/bin:/user/liuh/.mujoco/mujoco200/bin:/user/liuh/.mujoco/mujoco200/bin:/user/liuh/.mujoco/mujoco200/bin:/home/liuh/.mujoco/mujoco200/bin
2024-12-30 19:09:07.898615: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1934] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
/user/liuh/miniconda3/envs/design-baselines/lib/python3.7/site-packages/transformers/tokenization_utils_base.py:1423: FutureWarning: The `max_len` attribute has been deprecated and will be removed in a future version, use `model_max_length` instead.
```
I don't know if this result is normal, but when I modify the function `np.load ()` in the file `dataset_builer.py` to add `allow_pickle=True`, the error becomes `OSError: Failed to interpret file '/user/liuh/miniconda3/envs/design-baseline/lib/python3.7/site-packages/design_bench_data/superconductor/superconductor-x-0.npy' as a pickle.`

Thanks.

**Comment by christopher-beckham** [comment]
Hi,

For the pickle loading error, can you try the branch I have pushed `chris/fixes-v2`? (i.e. `git checkout chris/fixes-v2`) It is yet to be merged into the mainline branch, but this also fixes the dead dataset URLs as well as possibly fixing your issue via https://github.com/brandontrabucco/design-bench/pull/21/commits/92ece3cb226d89d113366051b7668187c58819b2

As for the other error, I don't use Tensorflow so my guess is as good as yours: some .so files are missing and cannot be found in `LD_LIBRARY_PATH` (or any other path that it may check). If it helps you, I have in another repository an installation readme which I use in order to reproduce a clean Conda environment for Design Bench, maybe it can help you with your Tensorflow problems: https://github.com/christopher-beckham/validation-metrics-offline-mbo/blob/port_eval/INSTALL.org

It appears that very specific versions of things are needed (including numpy) to ensure things don't break. Also can you list what version of numpy you're using (via `numpy.__version__`)? Thanks.

Hope this helps.

**Comment by Harkool** [comment]
Hello:
I tried the branch you pushed and ran it, but still got some errors, the errors is as follows: 
```
 pickle.UnpicklingError: invalid load key, 'v'. The above exception was the direct cause of the following exception: _pickle.UnpicklingError: Failed to interpret file '/user/liuh/miniconda3/envs/mbo/lib/python3.8/site-packages/design_bench_data/tf_bind_8-SIX6_REF_R1/tf_bind_8-x-0.npy' as a pickle`.
```

```
  File "/user/liuh/miniconda3/envs/mbo/lib/python3.8/site-packages/ray/tune/tune.py", line 543, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [reinforce_6c6ac_00000, reinforce_6c6ac_00001, reinforce_6c6ac_00002, reinforce_6c6ac_00003, reinforce_6c6ac_00004, reinforce_6c6ac_00005, reinforce_6c6ac_00006, reinforce_6c6ac_00007])
```

 In addition, the version of numpy  I am currently using is `1.22.0.`

Thanks.

**Comment by christopher-beckham** [comment]
Hi,

That is really strange. I am able to load either of those two .npy files with `np.load(filename)`, even with `allow_pickle=True` set. I just tried them and I also have `1.22.0` for my numpy version. These are the md5 checksums I have (using `md5sum`):

```
9536e6879c17ffa6f73bd57f90cbbc74  superconductor-x-0.npy
f585f593714004e00e26be0365971f91  tf_bind_8-x-0.npy
```

When did you originally download the data? A while back this library "broke" since the original data files on Google Cloud disappeared. (Earlier this year I was helping to recover as much of it as I could + also hosting the data on HuggingFace, hence the the `chris/fixes-v2` branch, but I still think we're missing some things.) But I'm just wondering if somehow the data you have is possibly corrupted. If you could just rename `design_bench_data` to something else (maybe keep it as a backup) and then re-run your code then it _should_ download them from scratch.

Side note: If your `design_bench_data` folder originated from long time ago, that could help me recover some files, depending on what you have. Everything I have is located here: https://huggingface.co/datasets/beckhamc/design_bench_data/tree/main

**Comment by Harkool** [comment]
Hi,
The issue has been resolved.  I found that the data downloaded at that time was corrupted, and it can run normally after updating the data. Using Hugging Face's dataset effectively solved the problem. Link as follows： [https://huggingface.co/datasets/beckhamc/design_bench_data/tree/main](https://huggingface.co/datasets/beckhamc/design_bench_data/tree/main`design_bench_data`
)`design_bench_data`
